apiVersion: v1
kind: Secret
metadata:
  name: nexchat-secrets
  namespace: nexchat
type: Opaque
stringData:
  secret-key: "nexchat-production-secret-key-2026"
  db-host: "10.0.1.49"
  db-password: "nexchat1234"